In [12]:
import semopy
import graphviz
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from warnings import filterwarnings
filterwarnings("ignore")

In [13]:
data = semopy.examples.political_democracy.get_data()
mod = semopy.examples.political_democracy.get_model()
m = semopy.Model(mod)
m.fit(data)
g = semopy.semplot(m, "pd.png")

In [14]:
df = pd.read_csv("./dummy_data.csv")
df.head()

,y1,y2,y3,y4,x2,x3,z2,y6,x6,x5,...,nx8,nx9,nx10,nx11,nx12,nx13,nx14,nx15,nx16,nx17
0,0.49,0.72,0.43,0.10,9376,0.75,65.95,0.86,29.08,0.94,...,78.05,72.74,67.22,86.75,69.65,70.40,71.25,71.36,54.42,42.69
1,0.48,0.72,0.42,0.10,10167,0.60,59.58,0.90,28.83,0.93,...,78.05,72.74,67.22,86.75,69.65,70.40,71.25,71.36,54.42,42.69
2,0.48,0.71,0.41,0.09,9790,0.68,62.19,0.90,30.47,0.93,...,78.05,72.74,67.22,86.75,69.65,70.40,71.25,71.36,54.42,42.69
3,0.48,0.71,0.41,0.10,10075,0.71,61.78,0.90,29.99,0.93,...,78.15,72.90,67.55,83.58,69.18,70.55,72.76,72.80,54.54,41.91
4,0.48,0.70,0.41,0.10,9713,0.72,62.17,0.90,29.91,0.92,...,78.15,72.90,67.55,83.58,69.18,70.55,72.76,72.80,54.54,41.91

In [15]:
# scale the data for better model fitting ? (not sure about this)
X = MinMaxScaler().fit_transform(df)
X = pd.DataFrame(X,columns=df.columns)

In [16]:
desc3 = """
et0 =~ G
eta1 =~ y1
eta2 =~ y2+y3+y4
y1 ~~ y2+y3+y4
eta2 ~ x1+x2+x3
eta1 ~ eta2
et0 ~ eta1+eta2
z2 ~ eta2
G ~ z2
"""

In [17]:
# create the model and fit the scaled data and see the result
mod = semopy.Model(desc3)
res = mod.fit(X)
print(res)

Name of objective: MLW
Optimization method: SLSQP
Optimization successful.
Optimization terminated successfully
Objective value: 3.607
Number of iterations: 80
Params: 0.649 -0.665 -0.035 -0.005 -0.002 0.000 0.000 0.000 0.005 0.048 0.000 0.017 0.038 0.023 0.365 0.047 -0.935 1.212 -3.544 4.248 0.539 0.366

In [18]:
# Finally let's inspect the parameters estimates
ins = mod.inspect()
print(ins)

WARNING:root:Fisher Information Matrix is not PD.Moore-Penrose inverse will be used instead of Cholesky decomposition. See 10.1109/TSP.2012.2208105.

    lval  op  rval      Estimate  Std. Err   z-value   p-value
0   eta2   ~    x1  3.646358e-01   0.21076  1.730097  0.083613
1   eta2   ~    x2  4.687477e-02  0.163266  0.287107   0.77403
2   eta2   ~    x3 -9.352574e-01  0.244834 -3.819971  0.000133
3   eta1   ~  eta2  1.212427e+00   0.29627  4.092304  0.000043
4    et0   ~  eta1 -3.544256e+00  0.522606 -6.781893       0.0
5    et0   ~  eta2  4.248402e+00  0.431075  9.855362       0.0
6     z2   ~  eta2  5.388508e-01  0.125618  4.289591  0.000018
7      G   ~   et0  1.000000e+00         -         -         -
8     y1   ~  eta1  1.000000e+00         -         -         -
9     y2   ~  eta2  1.000000e+00         -         -         -
10    y3   ~  eta2  6.490229e-01  0.120281   5.39588       0.0
11    y4   ~  eta2 -6.653681e-01   0.16928 -3.930586  0.000085
12     G   ~    z2  3.659957e-01  0.366812  0.997774  0.318389
13   et0  ~~   et0  3.174386e-12  0.019441       0.0       1.0
14  eta1  ~~  eta1  4.731178e-03  0.003741  1.264844  0.205927
15  eta2  ~~  eta2  4.830754e-02  0.015712  3.074568  0.002108
16    z2  ~~    z2  2.340404e-02  0.006993  3.346598  0.000818
17    y1  ~~    y2 -3.545510e-02  0.011953 -2.966333  0.003014
18    y1  ~~    y3 -5.280404e-03  0.010798 -0.489009  0.624835
19    y1  ~~    y4 -1.967365e-03  0.013482 -0.145928  0.883978
20    y1  ~~    y1  2.647040e-11  0.024835       0.0       1.0
21     G  ~~     G  0.000000e+00  0.019441       0.0       1.0
22    y2  ~~    y2  0.000000e+00  0.006899       0.0       1.0
23    y3  ~~    y3  1.694857e-02  0.006353  2.667761  0.007636
24    y4  ~~    y4  3.766173e-02   0.01292  2.914973  0.003557

In [19]:
# visualize the result
g = semopy.semplot(mod,"pd1.png")
print(g)

WARNING:root:Fisher Information Matrix is not PD.Moore-Penrose inverse will be used instead of Cholesky decomposition. See 10.1109/TSP.2012.2208105.

digraph G {
	overlap=scale splines=true
	edge [fontsize=12]
	node [fillcolor="#cae6df" shape=circle style=filled]
	eta2 [label=eta2]
	eta1 [label=eta1]
	et0 [label=et0]
	node [shape=box style=""]
	G [label=G]
	y1 [label=y1]
	y2 [label=y2]
	y3 [label=y3]
	y4 [label=y4]
	x1 [label=x1]
	x2 [label=x2]
	x3 [label=x3]
	z2 [label=z2]
	x1 -> eta2 [label="0.365\np-val: 0.08"]
	x2 -> eta2 [label="0.047\np-val: 0.77"]
	x3 -> eta2 [label="-0.935\np-val: 0.00"]
	eta2 -> eta1 [label="1.212\np-val: 0.00"]
	eta1 -> et0 [label="-3.544\np-val: 0.00"]
	eta2 -> et0 [label="4.248\np-val: 0.00"]
	eta2 -> z2 [label="0.539\np-val: 0.00"]
	et0 -> G [label=1.000]
	eta1 -> y1 [label=1.000]
	eta2 -> y2 [label=1.000]
	eta2 -> y3 [label="0.649\np-val: 0.00"]
	eta2 -> y4 [label="-0.665\np-val: 0.00"]
	z2 -> G [label="0.366\np-val: 0.32"]
}